apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: holamundo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: holamundo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: holamundo
    spec:
      containers:
      - name: holamundo-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        #image: wizplaycluster.icp:8500/default/hello-container:latest
        # for local development against minikube registry
        #imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: holamundo-service
  labels:
    app: holamundo-service
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 80
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: holamundo

---
#apiVersion: autoscaling/v1
#kind: HorizontalPodAutoscaler
#metadata:
#  name: holamundo-autoscaler
#spec:
#  scaleTargetRef:
#    kind: Deployment
#    name: holamundo
#  minReplicas: 2
#  maxReplicas: 5
#  targetCPUUtilizationPercentage: 20
