apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: holamundo-deployment
  labels:
    app: holamundo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: holamundo
    spec:
      containers:
      - name: holamundo
        image:  mycluster.icp:8500/default/holamundo-container
        resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: env_var_1_name
              value: env_var_1_value
          #  - name: cloudant_credentials
          #    valueFrom:
          #      secretKeyRef:
          #        name: cloudant-credentials
          #        key: credentials
          ports:
          - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: holamundo-service
  labels:
    app: holamundo
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
      NodePort: 31325
      protocol: TCP
      name: http
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: holamundo
