apiVersion: v1
kind: Service
metadata:
  name: holamundo-service
  labels:
    app: holamundo
spec:
  type: NodePort
  #type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31325
    protocol: TCP
    name: http
  #externalIPs:
  #  - 169.51.3.239
  selector:
    app: holamundo
